version: '3.4'

services:
  neo4j:
    container_name: neo4j_container
    image: neo4j:3.0
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      # 永続化するときにマウントするdir
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/conf:/conf
